# Beer configuration data

[domains]
path_to_domains_folder = "src/domain"

[architecture]
type = "legacy"
domains_folder_name = "domain"

[elements]

[elements.component]
  elementFolder = "ui/components"

[elements.hook]
  elementFolder = "ui/hook"

[elements.service]
  elementFolder = "application/service"



