# Beer configuration data

[domains]
pathToDomainsFolder = "src/domain"
includes=[]
excludes=[]

[architecture]
type = "legacy"

[reactElements]

  [reactElements.component]
    elementFolder = "components"
    reactElementType = "component"
    elementTestTitle = "Domains | :domainName | Components | :reactElementName"
    elementAbsolutePath = "@domains/:domainName/components/:reactElementName"

  [reactElements.hook]
    elementFolder = "ui/hooks"
    reactElementType = "hook"
    elementTestTitle = "Domains | :domainName | UI | Hooks | :reactElementName"
    elementAbsolutePath = "@domains/:domainName/ui/hooks/:reactElementName"

  [reactElements.context]
    elementFolder = "contexts"
    reactElementType = "context"
    elementTestTitle = "Domains | :domainName | Context | :reactElementName"
    elementAbsolutePath = "@domains/:domainName/context/:reactElementName"


