# Beer configuration data

[domains]
directories_path = "src/domains"

[architecture]
type = "default"
domains_folder_name = "domains"

[elements]

[elements.component]
  elementFolder = "ui/components"
  elementTestTitle = "Domains | :domainName | UI | Components | :elementName"

[elements.hook]
  elementFolder = "ui/hook"
  elementTestTitle= "Domains | :domainName | UI | Components | :elementName"

[elements.service]
  elementFolder = "application/service"
  elementTestTitle= "Domains | :domainName | UI | Components | :elementName"



