# Beer configuration data

[domains]
pathToDomainsFolder = "src/domains"
includes=[]
excludes=[]

[react-elements]

[react-elements.component]
  folder = "components"
  type = "component"

[react-elements.hook]
  folder = "hooks"
  type = "hook"

[react-elements.context]
  folder = "context"
  type = "context"
