# Beer configuration data

[domains]
pathToDomainsFolder = "src/domains"
includes=[]
excludes=[]

[react-elements]

[react-elements.component]
  folder = "components"
  type = "component"
  testTitle = "Domains | :domainName | Components | :elementName"
  absolutePath = "@domains/:domainName/components/:elementName"

[react-elements.hook]
  folder = "hooks"
  type = "hook"
  testTitle = "Domains | :domainName | Hooks | :elementName"
  absolutePath = "@domains/:domainName/hooks/:elementName"


