name: Publish Package
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/beer
    steps:
      - uses: actions/checkout@v4
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          registry-url: "https://registry.npmjs.org"
      # Removing the package.json file to disbale Yarn Worskpace behavior. Reach out the docs to understand the rationale
      - name: Removing Yarn Workspace Package.json
        run: rm ../../package.json
      - name: Install Project
        run: yarn
      - name: Build Project
        run: yarn build
      - name: Publish Project
        run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
